[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#E94057"
backgroundColor = "#121212"
secondaryBackgroundColor = "#1E1E1E"
textColor = "#F8F9FA"
font = "sans serif"
